'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '../..');
const mainSource = fs.readFileSync(path.join(root, 'src/electron/main.js'), 'utf8');
const agentSource = fs.readFileSync(path.join(root, 'src/agent/agent.js'), 'utf8');
const nodeHubSource = fs.readFileSync(path.join(root, 'src/hub/server.js'), 'utf8');
const workerHubSource = fs.readFileSync(path.join(root, 'worker/src/index.js'), 'utf8');
const hubProtocolSource = fs.readFileSync(path.join(root, 'src/shared/hubProtocol.js'), 'utf8');
const workerProtocolSource = fs.readFileSync(path.join(root, 'worker/src/shared/hubProtocol.js'), 'utf8');
const benchmarkSource = fs.readFileSync(path.join(root, 'scripts/benchmark-hub-bandwidth.js'), 'utf8');

test('official producers request the optional minimal ingest response', () => {
  assert.match(mainSource, /\[HUB_RESPONSE_HEADER\]: HUB_RESPONSE_MINIMAL/);
  assert.match(agentSource, /\[HUB_RESPONSE_HEADER\]: HUB_RESPONSE_MINIMAL/);
});

test('the desktop stream negotiates and applies freshness without losing legacy events', () => {
  assert.match(mainSource, /\[HUB_STREAM_HEADER\]: HUB_STREAM_VERSION/);
  assert.match(mainSource, /parsed\.event === 'stats' \|\| parsed\.event === 'snapshot'/);
  assert.match(mainSource, /applyFreshnessEvent\(latestHubStats, parsed\.data\)/);
});

test('Node and Worker hubs prepare SSE frames once and force full stats for delete or subscription writes', () => {
  assert.match(hubProtocolSource, /function prepareSseFanout/);
  assert.match(hubProtocolSource, /function encodeSseEvent/);
  assert.match(workerProtocolSource, /@generated by scripts\/sync-worker-shared\.js/);
  assert.match(workerProtocolSource, /function prepareSseFanout/);

  assert.match(nodeHubSource, /prepareSseFanout\(/);
  assert.match(nodeHubSource, /sseFrameForClient\(/);
  assert.match(nodeHubSource, /allowFreshness: false/);
  assert.match(nodeHubSource, /encodeSseEvent\('snapshot'/);
  assert.match(workerHubSource, /hubProtocol\.prepareSseFanout\(/);
  assert.match(workerHubSource, /hubProtocol\.sseFrameForClient\(/);
  assert.match(workerHubSource, /allowFreshness: false/);
  assert.match(workerHubSource, /hubProtocol\.encodeSseEvent\('snapshot'/);

  assert.match(nodeHubSource, /broadcastStats\('delete'\)/);
  assert.match(nodeHubSource, /broadcastStats\('subscriptions'\)/);
  assert.match(workerHubSource, /this\.broadcast\('delete'\)/);
  assert.match(workerHubSource, /this\.broadcast\('subscriptions'\)/);
});

test('the hub bandwidth benchmark still compares Node and Worker wire sizes from one stringify per frame', () => {
  assert.match(benchmarkSource, /function sse\(event, data\) \{[\s\S]*?JSON\.stringify\(data\)/);
  assert.match(benchmarkSource, /assert\.deepEqual\(workerRecord, nodeRecord/);
  assert.match(benchmarkSource, /Node and Worker aggregate stats drifted/);
  assert.match(benchmarkSource, /burst10NewPerClient: bytes\(burstEvents\.at\(-1\)\)/);
});
