// @generated by scripts/sync-worker-shared.js — DO NOT EDIT.
// Edit src/shared/<name>.js instead, then run `npm run sync:worker`.

'use strict';

// DeepSeek Harness (DSH) resolves its home directory in this order. Keep this
// module free of Node built-ins so the source-check id and resolver can be
// vendored with the Worker shared closure without making the Worker
// filesystem-aware (the same contract as reasonixPaths.js).
//
// DSH stores zstd-packed session logs at <DSH_HOME>/sessions/**/session.jsonl.zstd.
// The home itself is the value of the DSH_HOME environment variable when set,
// and otherwise the platform-default ~/.dsh (a flat dot-directory on every
// platform — DSH does not use XDG/AppData redirects for its home).
const DSH_CLIENT = 'dsh';
const DSH_SOURCE_CHECK_ID = 'dsh-sessions';

function nonEmpty(value) {
  const text = String(value ?? '').trim();
  return text || '';
}

function homeDirFor({ env = {}, homeDir = '', platform = '' } = {}) {
  const configured = nonEmpty(homeDir);
  if (configured) return configured;
  if (platform === 'win32') {
    return nonEmpty(env.USERPROFILE)
      || nonEmpty(env.HOME)
      || joinPath(platform, env.HOMEDRIVE, env.HOMEPATH);
  }
  return nonEmpty(env.HOME);
}

function joinPath(platform, root, ...parts) {
  const windows = platform === 'win32';
  const separator = windows ? '\\' : '/';
  let current = nonEmpty(root);
  for (const part of parts) {
    const next = nonEmpty(part);
    if (!next) continue;
    if (!current) {
      current = next;
    } else {
      current = `${current.replace(/[\\/]+$/, '')}${separator}${next.replace(/^[\\/]+/, '')}`;
    }
  }
  return current;
}

function isAbsolutePath(value, platform) {
  if (platform === 'win32') return /^\\\\/.test(value) || /^\\/.test(value) || /^[A-Za-z]:[\\/]/.test(value);
  return value.startsWith('/');
}

function normalizePosixPath(value) {
  const absolute = value.startsWith('/');
  const stack = [];
  for (const segment of value.split('/')) {
    if (!segment || segment === '.') continue;
    if (segment === '..') {
      if (stack.length > 0 && stack.at(-1) !== '..') stack.pop();
      else if (!absolute) stack.push(segment);
    } else {
      stack.push(segment);
    }
  }
  const normalized = stack.join('/');
  if (absolute) return `/${normalized}`;
  return normalized || '.';
}

function normalizeWindowsPath(value) {
  const input = value.replace(/\//g, '\\');
  let root = '';
  let rest = input;
  let absolute = false;

  if (input.startsWith('\\\\')) {
    const parts = input.slice(2).split('\\');
    const server = parts.shift() || '';
    const share = parts.shift() || '';
    root = `\\\\${server}${share ? `\\${share}` : ''}`;
    rest = parts.join('\\');
    absolute = true;
  } else if (/^[A-Za-z]:/.test(input)) {
    root = input.slice(0, 2);
    rest = input.slice(2);
    if (rest.startsWith('\\')) {
      root += '\\';
      rest = rest.slice(1);
      absolute = true;
    }
  } else if (input.startsWith('\\')) {
    root = '\\';
    rest = input.slice(1);
    absolute = true;
  }

  const stack = [];
  for (const segment of rest.split('\\')) {
    if (!segment || segment === '.') continue;
    if (segment === '..') {
      if (stack.length > 0 && stack.at(-1) !== '..') stack.pop();
      else if (!absolute) stack.push(segment);
    } else {
      stack.push(segment);
    }
  }

  const suffix = stack.join('\\');
  if (root) {
    if (!suffix) return root;
    return root.endsWith('\\') ? `${root}${suffix}` : `${root}\\${suffix}`;
  }
  return suffix || '.';
}

function normalizePath(value, platform) {
  return platform === 'win32' ? normalizeWindowsPath(value) : normalizePosixPath(value);
}

function currentDirectory({ env = {}, cwdDir = '' } = {}) {
  if (nonEmpty(cwdDir)) return nonEmpty(cwdDir);
  if (nonEmpty(env.PWD)) return nonEmpty(env.PWD);
  if (nonEmpty(env.INIT_CWD)) return nonEmpty(env.INIT_CWD);
  return typeof process !== 'undefined' && typeof process.cwd === 'function' ? process.cwd() : '';
}

// Mirrors the Reasonix cleanEnvDir semantics: expand the home shorthand, make
// relative paths absolute, and clean separators / dot segments before the
// caller appends 'sessions'.
function cleanEnvDir(value, options = {}) {
  const platform = options.platform || '';
  let cleaned = nonEmpty(value);
  if (!cleaned) return '';

  cleaned = cleaned.trim();
  if (!cleaned) return '';

  const homeDir = homeDirFor(options);
  if (cleaned === '~' || cleaned.startsWith('~/') || cleaned.startsWith('~\\')) {
    cleaned = joinPath(platform, homeDir, cleaned.slice(1));
  }

  if (!isAbsolutePath(cleaned, platform)) {
    const cwd = currentDirectory(options);
    if (cwd) cleaned = joinPath(platform, cwd, cleaned);
  }
  return normalizePath(cleaned, platform);
}

function resolveDshHome(options = {}) {
  const platform = options.platform || '';
  const configuredHome = cleanEnvDir((options.env || {}).DSH_HOME, options);
  if (configuredHome) return configuredHome;

  const homeDir = homeDirFor(options);
  return normalizePath(joinPath(platform, homeDir, '.dsh'), platform);
}

function resolveDshSessionsDir(options = {}) {
  const platform = options.platform || '';
  return normalizePath(joinPath(platform, resolveDshHome(options), 'sessions'), platform);
}

module.exports = {
  DSH_CLIENT,
  DSH_SOURCE_CHECK_ID,
  cleanEnvDir,
  resolveDshHome,
  resolveDshSessionsDir
};
