// @generated by scripts/sync-worker-shared.js — DO NOT EDIT.
// Edit src/shared/<name>.js instead, then run `npm run sync:worker`.

'use strict';

// Keep provider order stable: it is also the default order for a new install.
// Saved user ordering is parsed separately and must not be overwritten.
const LIMIT_PROVIDER_IDS = Object.freeze([
  'claude', 'codex', 'opencode', 'cursor', 'antigravity', 'kimi', 'grok',
  'copilot', 'commandcode', 'mimo', 'zai', 'zaiteam', 'kiro', 'workbuddy',
  'qoder', 'deepseek', 'openrouter', 'minimax', 'volcengine', 'ollama', 'trae',
  'thirdparty'
]);

// These are the only window metrics that cross the shared limits schema.
const LIMIT_WINDOW_METRICS = Object.freeze(['credits', 'spend']);
const VALID_LIMIT_WINDOW_METRICS = new Set(LIMIT_WINDOW_METRICS);

// Initial discovery is deliberately narrower than the provider list: only a
// provider with the same id as a detected local client can be seeded. A
// `waiting` client has a real source directory but no usage yet, so it must be
// included just like an `active` client; `missing` means the source probe found
// nothing and must stay disabled.
function limitProvidersForDetectedClients(clientStatus) {
  const detected = new Set(
    Object.entries(clientStatus || {})
      .filter(([, status]) => status === 'active' || status === 'waiting')
      .map(([client]) => String(client).trim().toLowerCase())
  );
  return LIMIT_PROVIDER_IDS.filter((provider) => detected.has(provider));
}

module.exports = {
  LIMIT_PROVIDER_IDS,
  LIMIT_WINDOW_METRICS,
  VALID_LIMIT_WINDOW_METRICS,
  limitProvidersForDetectedClients
};
