// @generated by scripts/sync-worker-shared.js — DO NOT EDIT.
// Edit the matching file under src/shared/ instead, then run `npm run sync:worker`.

'use strict';

// Live Activity content state v2: the Hub push builder emits the structured
// payload the iOS extension decodes into TokenMonitorActivityAttributes
// .ContentState — no pre-formatted strings cross the wire; the device renders
// and localises. Keep the field names identical to the Swift struct.

const { creditsMeterPercent } = require('./limits/balanceDisplay');
const { LIMIT_PROVIDER_IDS } = require('./limits/providers');
const { limitWindowLabel } = require('./limits/windowLabels');

const DATE_REFERENCE_SECONDS = 978307200;
const STALE_AGE_SECONDS = 15 * 60;
const VALID_CURRENCIES = new Set(['USD', 'TWD', 'HKD', 'CNY']);
const VALID_LANGUAGES = new Set(['auto', 'en', 'zh-TW', 'zh-CN', 'ja', 'ko']);
const VALID_PERIODS = new Set(['today', 'month', 'allTime']);
const VALID_COMPACT_LEADING = new Set(['mark', 'ring', 'tokens', 'cost']);
const VALID_COMPACT_TRAILING = new Set(['percent', 'reset', 'tokens', 'cost', 'ring']);
const VALID_STYLES = new Set(['quota', 'usage', 'combined']);

function asNumber(value) {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string' && value.trim() !== '') {
    const parsed = Number(value.replace(/[%,$]/g, ''));
    if (Number.isFinite(parsed)) return parsed;
  }
  return null;
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function normalizedString(value, maxLength = 128) {
  const text = String(value || '').trim();
  return text ? text.slice(0, maxLength) : '';
}

function normalizedProvider(value) {
  const provider = normalizedString(value, 64).toLowerCase();
  return provider || null;
}

function normalizedOption(value, valid, fallback) {
  const option = normalizedString(value, 32);
  return valid.has(option) ? option : fallback;
}

function languageLocale(languageCode, locale) {
  if (languageCode === 'en') return 'en';
  if (languageCode === 'zh-TW') return 'zh-Hant';
  if (languageCode === 'zh-CN') return 'zh-Hans';
  if (languageCode === 'ja') return 'ja';
  if (languageCode === 'ko') return 'ko';
  return normalizedString(locale, 64) || 'en';
}

function normalizeLiveActivityRegistration(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) {
    throw new Error('invalid_live_activity_registration');
  }
  const activityID = typeof input.activityID === 'string' ? input.activityID.trim() : '';
  const token = typeof input.token === 'string' ? input.token.trim().toLowerCase() : '';
  if (!/^[A-Za-z0-9_-]{1,128}$/.test(activityID) || !/^(?:[0-9a-f]{2}){16,2048}$/.test(token)) {
    throw new Error('invalid_live_activity_registration');
  }

  const raw = input.preferences && typeof input.preferences === 'object'
    ? input.preferences
    : {};
  const languageCode = VALID_LANGUAGES.has(raw.languageCode)
    ? raw.languageCode
    : 'auto';
  const currencyCode = VALID_CURRENCIES.has(raw.currencyCode)
    ? raw.currencyCode
    : 'USD';

  return {
    activityID,
    token,
    locale: languageLocale(languageCode, input.locale),
    registeredAt: new Date().toISOString(),
    preferences: {
      liveActivityEnabled: raw.liveActivityEnabled !== false,
      livePeriod: VALID_PERIODS.has(raw.livePeriod) ? raw.livePeriod : 'today',
      liveProviderID: normalizedProvider(raw.liveProviderID),
      liveCompactLeading: normalizedOption(raw.liveCompactLeading, VALID_COMPACT_LEADING, 'mark'),
      liveCompactTrailing: normalizedOption(raw.liveCompactTrailing, VALID_COMPACT_TRAILING, 'percent'),
      liveExpandedStyle: normalizedOption(raw.liveExpandedStyle, VALID_STYLES, 'quota'),
      liveLockScreenStyle: normalizedOption(raw.liveLockScreenStyle, VALID_STYLES, 'combined'),
      currencyCode,
      languageCode
    }
  };
}

function providerWindowRemaining(provider, window) {
  if (window?.metric === 'credits') return creditsMeterPercent(provider, window);
  const explicit = asNumber(window?.remainingPercent);
  if (explicit !== null) return clamp(explicit, 0, 100);
  const usedPercent = asNumber(window?.usedPercent);
  return usedPercent === null ? null : clamp(100 - usedPercent, 0, 100);
}

function displayWindows(provider) {
  return (Array.isArray(provider?.windows) ? provider.windows : []).filter((window) => (
    window?.metric === 'credits'
      || providerWindowRemaining(provider, window) !== null
      || asNumber(window?.remaining) !== null
      || asNumber(window?.used) !== null
      || String(window?.detail || '').trim() !== ''
  ));
}

// The shared views show the canonical lanes only; promo/additional windows
// never reach the island or lock screen.
function canonicalWindows(provider) {
  return displayWindows(provider).filter((window) => window?.additional !== true);
}

function lowestRemaining(provider) {
  const values = canonicalWindows(provider)
    .map((window) => providerWindowRemaining(provider, window))
    .filter((value) => value !== null);
  return values.length ? Math.min(...values) : null;
}

function providerStatus(provider) {
  return normalizedProvider(provider?.status) || 'ok';
}

function catalogIndex(provider) {
  const index = LIMIT_PROVIDER_IDS.indexOf(normalizedProvider(provider?.provider));
  return index === -1 ? LIMIT_PROVIDER_IDS.length : index;
}

// Identical to the Swift auto pick: healthy (status ok / absent) non-stale
// providers, the lowest canonical remaining % wins; ties and empty pools fall
// back to the default catalog order.
function selectLiveActivityProvider(stats, providerID) {
  const providers = Array.isArray(stats?.limits?.providers)
    ? stats.limits.providers
    : [];
  if (!providers.length) return null;
  if (providerID) {
    const matches = providers.filter((provider) => (
      normalizedProvider(provider?.provider) === providerID
    ));
    if (!matches.length) return null;
    return matches.reduce((best, provider) => {
      if (!best) return provider;
      const left = lowestRemaining(provider);
      const right = lowestRemaining(best);
      if (left === null) return best;
      if (right === null || left < right) return provider;
      return best;
    }, null);
  }
  const eligible = providers.filter((provider) => (
    providerStatus(provider) === 'ok' && provider?.stale !== true
  ));
  const pool = eligible.length ? eligible : providers;
  return pool.reduce((best, provider) => {
    if (!best) return provider;
    const left = lowestRemaining(provider);
    const right = lowestRemaining(best);
    if (left === null) {
      // No candidate has a meter yet — catalog order decides.
      return right === null && catalogIndex(provider) < catalogIndex(best)
        ? provider
        : best;
    }
    if (right === null || left < right) return provider;
    return left === right && catalogIndex(provider) < catalogIndex(best)
      ? provider
      : best;
  }, null);
}

function sourceTimestamp(value, nowMs) {
  if (typeof value !== 'string' || !value.trim()) return null;
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) && parsed <= nowMs ? parsed : null;
}

function appleSeconds(timestampMs) {
  return timestampMs === null ? null
    : Math.floor(timestampMs / 1000) - DATE_REFERENCE_SECONDS;
}

// The top-level timestamp describes the usage feed (devices first, then the
// stats envelope) — the quota carries its own updatedAt/stale.
function activitySource(stats, nowMs) {
  const devices = Array.isArray(stats?.devices) ? stats.devices : [];
  let milliseconds;
  let stale;
  if (devices.length) {
    const timestamps = devices.map((device) => sourceTimestamp(device?.updatedAt, nowMs))
      .filter((value) => value !== null);
    milliseconds = timestamps.length ? Math.max(...timestamps) : null;
    stale = devices.every((device) => device?.stale === true);
  } else {
    milliseconds = sourceTimestamp(stats?.updatedAt, nowMs);
    stale = false;
  }
  return {
    // An unknown source must never acquire the transport's current timestamp.
    updatedAt: appleSeconds(milliseconds) ?? -DATE_REFERENCE_SECONDS,
    sourceStale: stale || milliseconds === null || nowMs - milliseconds >= STALE_AGE_SECONDS * 1000
  };
}

function liveActivityStaleDate(contentState, timestamp) {
  const updatedAt = contentState?.updatedAt;
  const sourceSeconds = typeof updatedAt === 'number' && Number.isFinite(updatedAt)
    ? Math.floor(updatedAt + DATE_REFERENCE_SECONDS)
    : null;
  if (sourceSeconds === null || sourceSeconds > timestamp) return timestamp;
  const deadline = sourceSeconds + STALE_AGE_SECONDS;
  // Explicit stale status can precede the fifteen-minute age threshold.
  return contentState?.sourceStale === true ? Math.min(deadline, timestamp) : deadline;
}

function quotaWindow(provider, providerID, window) {
  const isCredits = window?.metric === 'credits';
  const credits = isCredits
    ? asNumber(window?.remaining) ?? asNumber(provider?.balance?.amount)
    : null;
  const currency = isCredits
    ? normalizedString(window?.currency, 8).toUpperCase()
      || normalizedString(provider?.balance?.currency, 8).toUpperCase() || null
    : null;
  return {
    label: limitWindowLabel(providerID, window, 'Quota'),
    remainingPercent: providerWindowRemaining(provider, window),
    resetsAt: appleSeconds(sourceTimestamp(window?.resetsAt, Number.MAX_SAFE_INTEGER)),
    creditsAmount: credits,
    creditsCurrency: currency
  };
}

function liveActivityQuota(stats, preferences, nowMs) {
  const provider = selectLiveActivityProvider(stats, preferences.liveProviderID);
  if (!provider) return null;
  const providerID = normalizedProvider(provider.provider);
  return {
    providerID,
    planLabel: normalizedString(provider.planLabel) || normalizedString(provider.accountLabel) || null,
    updatedAt: appleSeconds(sourceTimestamp(provider.updatedAt, nowMs)),
    stale: provider.stale === true || null,
    windows: canonicalWindows(provider).slice(0, 2)
      .map((window) => quotaWindow(provider, providerID, window))
  };
}

function layoutFor(preferences) {
  return {
    compactLeading: normalizedOption(preferences.liveCompactLeading, VALID_COMPACT_LEADING, 'mark'),
    compactTrailing: normalizedOption(preferences.liveCompactTrailing, VALID_COMPACT_TRAILING, 'percent'),
    expanded: normalizedOption(preferences.liveExpandedStyle, VALID_STYLES, 'quota'),
    lockScreen: normalizedOption(preferences.liveLockScreenStyle, VALID_STYLES, 'combined'),
    currencyCode: VALID_CURRENCIES.has(preferences.currencyCode)
      ? preferences.currencyCode
      : 'USD',
    languageCode: VALID_LANGUAGES.has(preferences.languageCode)
      ? preferences.languageCode
      : 'auto'
  };
}

function buildLiveActivityContentState(stats, registration, nowMs = Date.now()) {
  const preferences = registration?.preferences || {};
  const period = VALID_PERIODS.has(preferences.livePeriod) ? preferences.livePeriod : 'today';
  const usage = stats?.periods?.[period] || {};
  return {
    ...activitySource(stats, nowMs),
    period,
    tokens: asNumber(usage.totalTokens),
    costUSD: asNumber(usage.costUsd),
    quota: liveActivityQuota(stats, preferences, nowMs),
    layout: layoutFor(preferences)
  };
}

module.exports = {
  liveActivityStaleDate,
  buildLiveActivityContentState,
  normalizeLiveActivityRegistration
};
