// @generated by scripts/sync-worker-shared.js — DO NOT EDIT.
// Edit the matching file under src/shared/ instead, then run `npm run sync:worker`.

'use strict';

const { creditsAmount, creditsCurrency, creditsMeterPercent, formatMoney } = require('./limits/balanceDisplay');

const DATE_REFERENCE_SECONDS = 978307200;
const VALID_CURRENCIES = new Set(['USD', 'TWD', 'HKD', 'CNY']);
const VALID_LANGUAGES = new Set(['auto', 'en', 'zh-TW', 'zh-CN', 'ja', 'ko']);
const VALID_FIELDS = new Set([
  'primary',
  'secondary',
  'provider',
  'tokens',
  'cost',
  'limit',
  'progress',
  'updated',
  'none'
]);
const VALID_METRICS = new Set(['tokens', 'cost', 'limit']);
const VALID_PERIODS = new Set(['today', 'month', 'allTime']);
const CURRENCY_RATES_FROM_USD = {
  USD: 1,
  TWD: 31.5,
  HKD: 7.8,
  CNY: 6.8
};
const CURRENCY_SYMBOLS = {
  USD: '$',
  TWD: 'NT$',
  HKD: 'HK$',
  CNY: '¥'
};
const PROVIDER_NAMES = {
  claude: 'Claude',
  codex: 'Codex',
  cursor: 'Cursor',
  antigravity: 'Antigravity',
  opencode: 'OpenCode',
  openrouter: 'OpenRouter',
  deepseek: 'DeepSeek',
  minimax: 'MiniMax',
  mimo: 'MiMo',
  grok: 'Grok',
  copilot: 'GitHub Copilot',
  kiro: 'Kiro',
  zai: 'Z.ai',
  zaiteam: 'Z.ai Team',
  volcengine: 'Volcengine',
  qoder: 'Qoder',
  kimi: 'Kimi',
  ollama: 'Ollama',
  thirdparty: 'Custom Provider'
};

function asNumber(value) {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string' && value.trim() !== '') {
    const parsed = Number(value.replace(/[%,$]/g, ''));
    if (Number.isFinite(parsed)) return parsed;
  }
  return null;
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function normalizedString(value, maxLength = 128) {
  const text = String(value || '').trim();
  return text ? text.slice(0, maxLength) : '';
}

function normalizedProvider(value) {
  const provider = normalizedString(value, 64).toLowerCase();
  return provider || null;
}

function normalizedField(value, fallback) {
  const field = normalizedString(value, 32);
  return VALID_FIELDS.has(field) ? field : fallback;
}

function languageLocale(languageCode, locale) {
  if (languageCode === 'en') return 'en';
  if (languageCode === 'zh-TW') return 'zh-Hant';
  if (languageCode === 'zh-CN') return 'zh-Hans';
  if (languageCode === 'ja') return 'ja';
  if (languageCode === 'ko') return 'ko';
  return normalizedString(locale, 64) || 'en';
}

function normalizeLiveActivityRegistration(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) {
    throw new Error('invalid_live_activity_registration');
  }
  const activityID = typeof input.activityID === 'string' ? input.activityID.trim() : '';
  const token = typeof input.token === 'string' ? input.token.trim().toLowerCase() : '';
  if (!/^[A-Za-z0-9_-]{1,128}$/.test(activityID) || !/^(?:[0-9a-f]{2}){16,2048}$/.test(token)) {
    throw new Error('invalid_live_activity_registration');
  }

  const raw = input.preferences && typeof input.preferences === 'object'
    ? input.preferences
    : {};
  const languageCode = VALID_LANGUAGES.has(raw.languageCode)
    ? raw.languageCode
    : 'auto';
  const currencyCode = VALID_CURRENCIES.has(raw.currencyCode)
    ? raw.currencyCode
    : 'USD';

  return {
    activityID,
    token,
    locale: languageLocale(languageCode, input.locale),
    registeredAt: new Date().toISOString(),
    preferences: {
      liveActivityEnabled: raw.liveActivityEnabled !== false,
      livePrimaryMetric: VALID_METRICS.has(raw.livePrimaryMetric)
        ? raw.livePrimaryMetric
        : 'tokens',
      livePeriod: VALID_PERIODS.has(raw.livePeriod)
        ? raw.livePeriod
        : 'today',
      liveProviderID: normalizedProvider(raw.liveProviderID),
      liveShowsSecondaryMetric: raw.liveShowsSecondaryMetric !== false,
      liveShowsProgress: raw.liveShowsProgress !== false,
      liveIconProviderID: normalizedProvider(raw.liveIconProviderID),
      liveCompactTrailingField: normalizedField(raw.liveCompactTrailingField, 'primary'),
      liveExpandedLeadingField: normalizedField(raw.liveExpandedLeadingField, 'provider'),
      liveExpandedCenterField: normalizedField(raw.liveExpandedCenterField, 'primary'),
      liveExpandedTrailingField: normalizedField(raw.liveExpandedTrailingField, 'secondary'),
      liveExpandedBottomField: normalizedField(raw.liveExpandedBottomField, 'progress'),
      liveLockScreenPrimaryField: normalizedField(raw.liveLockScreenPrimaryField, 'primary'),
      liveLockScreenSecondaryField: normalizedField(raw.liveLockScreenSecondaryField, 'secondary'),
      liveLockScreenBottomField: normalizedField(raw.liveLockScreenBottomField, 'progress'),
      currencyCode,
      languageCode
    }
  };
}

function localeFor(registration) {
  return registration.locale || languageLocale(
    registration.preferences?.languageCode,
    undefined
  );
}

function formatNumber(value, locale, options = {}) {
  const number = Number.isFinite(value) ? value : 0;
  try {
    return new Intl.NumberFormat(locale, options).format(number);
  } catch (_) {
    return new Intl.NumberFormat('en', options).format(number);
  }
}

function formatTokens(value, locale) {
  return formatNumber(value, locale, {
    notation: 'compact',
    maximumFractionDigits: 1
  });
}

function formatCurrencyFromUSD(value, currencyCode, locale) {
  const code = VALID_CURRENCIES.has(currencyCode) ? currencyCode : 'USD';
  const converted = (Number.isFinite(value) ? value : 0) * CURRENCY_RATES_FROM_USD[code];
  return CURRENCY_SYMBOLS[code] + formatNumber(converted, locale, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  });
}

function languageFamily(locale) {
  const identifier = String(locale || '').toLowerCase();
  if (identifier.startsWith('zh-hant') || identifier.startsWith('zh-tw') || identifier.startsWith('zh-hk')) {
    return 'zh-Hant';
  }
  if (identifier.startsWith('zh')) return 'zh-Hans';
  if (identifier.startsWith('ja')) return 'ja';
  if (identifier.startsWith('ko')) return 'ko';
  return 'en';
}

function formatRemaining(value, locale) {
  const percentage = formatNumber(clamp(Number(value) || 0, 0, 100) / 100, locale, {
    style: 'percent',
    maximumFractionDigits: 0
  });
  switch (languageFamily(locale)) {
    case 'zh-Hant': return `${percentage} 剩餘`;
    case 'zh-Hans': return `${percentage} 剩余`;
    case 'ja': return `残り ${percentage}`;
    case 'ko': return `${percentage} 남음`;
    default: return `${percentage} left`;
  }
}

function providerName(providerID) {
  const normalized = normalizedProvider(providerID);
  if (!normalized) return 'Provider';
  return PROVIDER_NAMES[normalized]
    || normalized.slice(0, 1).toUpperCase() + normalized.slice(1);
}

function modelVendor(modelID) {
  const model = String(modelID || '').toLowerCase();
  if (model === 'auto' || model === 'cursor-auto') return 'cursor';
  if (/claude|anthropic|sonnet|opus|haiku/.test(model)) return 'claude';
  if (/gpt|openai|codex|chatgpt|^o[134](?:-|$)/.test(model)) return 'codex';
  if (/gemini|gemma|google/.test(model)) return 'gemini';
  if (/grok|xai/.test(model)) return 'grok';
  if (/deepseek/.test(model)) return 'deepseek';
  if (/llama|meta/.test(model)) return 'meta';
  if (/mistral|mixtral|codestral/.test(model)) return 'mistral';
  if (/qwen|qwq|qvq/.test(model)) return 'qwen';
  if (/kimi|moonshot/.test(model)) return 'kimi';
  if (/chatglm|glm-|z\.ai|zhipu/.test(model)) return 'zai';
  if (/cohere|command-r/.test(model)) return 'cohere';
  if (/mimo|xiaomi/.test(model)) return 'xiaomi';
  if (/minimax|abab/.test(model)) return 'minimax';
  if (/doubao|^seed-/.test(model)) return 'doubao';
  if (model === 'big-pickle') return 'opencode';
  return null;
}

function providerWindowRemaining(provider, window) {
  if (window?.metric === 'credits') return creditsMeterPercent(provider, window);
  const explicit = asNumber(window?.remainingPercent);
  if (explicit !== null) return clamp(explicit, 0, 100);
  const usedPercent = asNumber(window?.usedPercent);
  return usedPercent === null ? null : clamp(100 - usedPercent, 0, 100);
}

function displayWindows(provider) {
  return (Array.isArray(provider?.windows) ? provider.windows : []).filter((window) => (
    window?.metric === 'credits'
      || providerWindowRemaining(provider, window) !== null
      || asNumber(window?.remaining) !== null
      || asNumber(window?.used) !== null
      || String(window?.detail || '').trim() !== ''
  ));
}

function preferredLimit(stats, providerID) {
  const providers = Array.isArray(stats?.limits?.providers)
    ? stats.limits.providers
    : [];
  if (providerID) {
    const selected = providers.find((provider) => (
      normalizedProvider(provider?.provider) === providerID
    ));
    return selected || null;
  }
  return providers.reduce((best, provider) => {
    if (!best) return provider;
    const left = Math.min(...displayWindows(provider)
      .map((window) => providerWindowRemaining(provider, window))
      .filter((value) => value !== null));
    const right = Math.min(...displayWindows(best)
      .map((window) => providerWindowRemaining(best, window))
      .filter((value) => value !== null));
    if (!Number.isFinite(left)) return best;
    if (!Number.isFinite(right) || left < right) return provider;
    return best;
  }, null) || providers[0] || null;
}

function sourceTimestamp(value, nowMs) {
  if (typeof value !== 'string' || !value.trim()) return null;
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) && parsed <= nowMs ? parsed : null;
}

function activitySource(stats, selectedLimit, primaryMetric, nowMs) {
  const devices = Array.isArray(stats?.devices) ? stats.devices : [];
  let milliseconds;
  let stale;
  if (primaryMetric === 'limit') {
    milliseconds = sourceTimestamp(selectedLimit?.updatedAt, nowMs);
    stale = selectedLimit?.stale === true;
  } else if (devices.length) {
    const timestamps = devices.map((device) => sourceTimestamp(device?.updatedAt, nowMs))
      .filter((value) => value !== null);
    milliseconds = timestamps.length ? Math.max(...timestamps) : null;
    stale = devices.every((device) => device?.stale === true);
  } else {
    milliseconds = sourceTimestamp(stats?.updatedAt, nowMs);
    stale = false;
  }
  return {
    // An unknown source must never acquire the transport's current timestamp.
    updatedAt: Math.floor((milliseconds ?? 0) / 1000) - DATE_REFERENCE_SECONDS,
    sourceStale: stale || milliseconds === null || nowMs - milliseconds >= 600_000
  };
}

function liveActivityStaleDate(contentState, timestamp) {
  const updatedAt = contentState?.updatedAt;
  const sourceSeconds = typeof updatedAt === 'number' && Number.isFinite(updatedAt)
    ? Math.floor(updatedAt + DATE_REFERENCE_SECONDS)
    : null;
  if (sourceSeconds === null || sourceSeconds > timestamp) return timestamp;
  const deadline = sourceSeconds + 600;
  // Explicit stale status can precede the ten-minute age threshold.
  return contentState?.sourceStale === true ? Math.min(deadline, timestamp) : deadline;
}

function buildLiveActivityContentState(stats, registration, nowMs = Date.now()) {
  const preferences = registration?.preferences || {};
  const locale = localeFor(registration || {});
  const period = stats?.periods?.[preferences.livePeriod] || {};
  const tokens = asNumber(period.totalTokens);
  const cost = asNumber(period.costUsd);
  const tokensValue = tokens === null ? '—' : formatTokens(tokens, locale);
  const costValue = cost === null ? '—' : formatCurrencyFromUSD(
    cost,
    preferences.currencyCode,
    locale
  );
  const selectedLimit = preferredLimit(stats, preferences.liveProviderID);
  const selectedProviderID = normalizedProvider(selectedLimit?.provider);
  const selectedWindow = displayWindows(selectedLimit)[0] || null;
  const remaining = selectedWindow
    ? providerWindowRemaining(selectedLimit, selectedWindow)
    : null;
  const limitValue = selectedWindow?.metric === 'credits'
    ? formatMoney(creditsAmount(selectedLimit, selectedWindow), creditsCurrency(selectedLimit, selectedWindow)) || '—'
    : remaining === null ? null : formatRemaining(remaining, locale);
  const modelIDs = Object.keys(period.models || {});
  const dataProviderID = selectedProviderID
    || preferences.liveProviderID
    || modelVendor(modelIDs[0]);
  const iconProviderID = preferences.liveIconProviderID
    || dataProviderID
    || modelVendor(modelIDs[0]);
  const dataProviderName = providerName(dataProviderID);

  let primaryLabel = 'Tokens';
  let primaryValue = tokensValue;
  if (preferences.livePrimaryMetric === 'cost') {
    primaryLabel = 'Cost';
    primaryValue = costValue;
  } else if (preferences.livePrimaryMetric === 'limit') {
    primaryLabel = dataProviderName;
    primaryValue = limitValue ?? '—';
  }

  const configuredFields = [
    preferences.liveCompactTrailingField,
    preferences.liveExpandedLeadingField,
    preferences.liveExpandedCenterField,
    preferences.liveExpandedTrailingField,
    preferences.liveExpandedBottomField,
    preferences.liveLockScreenPrimaryField,
    preferences.liveLockScreenSecondaryField,
    preferences.liveLockScreenBottomField
  ];
  const showSecondary = preferences.liveShowsSecondaryMetric
    || configuredFields.includes('secondary');
  const showProgress = preferences.liveShowsProgress
    || configuredFields.includes('progress');
  let secondaryLabel = null;
  let secondaryValue = null;
  if (showSecondary && preferences.livePrimaryMetric === 'limit') {
    secondaryLabel = 'Cost';
    secondaryValue = costValue;
  } else if (showSecondary && limitValue !== null) {
    secondaryLabel = dataProviderName;
    secondaryValue = limitValue;
  }

  return {
    primaryLabel,
    primaryValue,
    secondaryLabel,
    secondaryValue,
    progress: showProgress && remaining !== null ? remaining / 100 : null,
    ...activitySource(stats, selectedLimit, preferences.livePrimaryMetric, nowMs),
    providerID: dataProviderID || null,
    providerName: dataProviderID ? dataProviderName : null,
    iconProviderID: iconProviderID || null,
    tokensValue,
    costValue,
    limitValue,
    compactTrailingField: preferences.liveCompactTrailingField,
    expandedLeadingField: preferences.liveExpandedLeadingField,
    expandedCenterField: preferences.liveExpandedCenterField,
    expandedTrailingField: preferences.liveExpandedTrailingField,
    expandedBottomField: preferences.liveExpandedBottomField,
    lockScreenPrimaryField: preferences.liveLockScreenPrimaryField,
    lockScreenSecondaryField: preferences.liveLockScreenSecondaryField,
    lockScreenBottomField: preferences.liveLockScreenBottomField
  };
}

module.exports = {
  liveActivityStaleDate,
  buildLiveActivityContentState,
  normalizeLiveActivityRegistration
};
