'use strict';
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const num = (v) => v == null ? '未知' : esc(Number(v).toLocaleString('en-US'));
function renderCloudHtml(r) {
  const threads = (r.threads || []).map((t) => `<tr><td><code>${esc(t.threadId)}</code><small>${esc(t.kind || '类型未知')}</small></td><td><small>引擎：${esc(t.engineParentId || '未知')}<br>委派：${esc(t.delegationParentId || '未知')}<br>dot：${esc(t.dotId || '未知')}</small></td><td>${esc(t.historyStatus)}</td><td>${num(t.turnCount)}</td></tr>`).join('');
  const turns = (r.turns || []).map((t) => `<tr><td><code>${esc(t.threadId)}</code><small>${esc(t.turnId)}</small></td><td>${esc(t.observedDate || '未知')}<small>${esc(t.dateBasis)}</small></td><td>${esc(t.model || '未知')}</td><td>${num(t.tokens?.inputTokens)}</td><td>${num(t.tokens?.cachedInputTokens)}</td><td>${num(t.tokens?.outputTokens)}</td><td>${num(t.tokens?.totalTokens)}</td><td>${t.estimatedUsdMicros == null ? '未知' : '$' + num(t.estimatedUsdMicros / 1e6)}</td></tr>`).join('');
  const quotas = (r.quotas || []).map((q) => `<tr><td><code>${esc(q.threadId)}</code></td><td>${q.fiveHourLimitPercent == null ? '未知' : num(q.fiveHourLimitPercent) + '%'}</td><td>${q.weeklyLimitPercent == null ? '未知' : num(q.weeklyLimitPercent) + '%'}</td><td>${esc(q.purchasedCredits ?? '未知')}</td><td>${esc(q.dataStatus || '未知')}</td></tr>`).join('');
  return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Codex 云端任务用量</title><style>body{font:15px/1.6 system-ui;margin:40px auto;max-width:1400px;padding:0 24px}h1{font-size:30px}h2{margin-top:34px}.note{background:#fff4db;padding:18px;border-left:4px solid #b58017}.wrap{overflow:auto}table{border-collapse:collapse;width:100%}td,th{padding:11px;text-align:left;border-bottom:1px solid #ddd;vertical-align:top}small{display:block;color:#666}code{font-size:11px;overflow-wrap:anywhere}.value{font-size:28px;font-weight:700}</style><small>TOKEN MONITOR · HOSTED CLOUD · PLANMETER-COMPATIBLE</small><h1>Codex 云端任务用量</h1><p>状态：<b>${esc(r.status)}</b> · ${esc(r.observedAt)}</p><p class="note">云端历史能读取，不代表 token 接口开放。缺失值不是零；费用是服务端估算，额度占比不是 token。此页不与账户累计或本地日志加总。</p><p>线程 ${num(r.threads?.length)} · 轮次 ${num(r.turns?.length)} · 有 Token 的轮次 ${num(r.totals?.tokenTurns)} · Token 缺失 ${num(r.totals?.missingTokenTurns)}</p><small>仅已观测且有去重依据的轮次合计，非完整云端账户总量</small><div class="value">${num(r.totals?.observedSettledTokens)} Token</div><p>逐轮接口：${esc(r.usageAccess || '不可用')} · 额度接口：${esc(r.quotaAccess || '未查询')}</p><h2>线程与委派关系</h2><div class="wrap"><table><thead><tr><th>线程</th><th>不同来源的关系</th><th>历史读取</th><th>轮次</th></tr></thead><tbody>${threads || '<tr><td colspan="4">尚无可用线程。</td></tr>'}</tbody></table></div><h2>逐轮 token 与费用估算</h2><div class="wrap"><table><thead><tr><th>线程／轮次 ID</th><th>UTC 日期</th><th>模型</th><th>Input</th><th>Cached（Input 子集）</th><th>Output</th><th>Total</th><th>估算 USD</th></tr></thead><tbody>${turns || '<tr><td colspan="8">尚无可用轮次。</td></tr>'}</tbody></table></div><h2>额度／购买 credits · 不折算 Token</h2><div class="wrap"><table><thead><tr><th>线程</th><th>5 小时占比</th><th>周占比</th><th>购买 credits 消耗</th><th>状态</th></tr></thead><tbody>${quotas || '<tr><td colspan="5">未查询或不可用。</td></tr>'}</tbody></table></div><h2>诊断</h2><p>${esc((r.diagnostics || []).map((d) => `${d.stage}: ${d.code}`).join(' · ') || '无额外诊断')}</p><small>本地静态文件，无网络资源或脚本。数据仅代表采集时状态；读取范围和历史分页均有上限。</small></html>`;
}
module.exports = { renderCloudHtml };
